%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/backend/TimeSeries/AGRO_SOFC/SOFC-REFORMER/2021-03-04-SOFC-REFORMER-Martin/A000_RelatedFiles/ReformerPlusStackData_small.csv
%
% Auto-generated by MATLAB on 11-Mar-2021 14:27:40

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 67);

% Specify range and delimiter
opts.DataLines = [7, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ReformerEntry", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "ReformerEXITCompositionFuelCellInletComposition", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "FUELCELL", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "FuelCellExhaust", "VarName49", "VarName50", "VarName51", "VarName52", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "VarName58", "VarName59", "VarName60", "VarName61", "VarName62", "VarName63", "VarName64", "VarName65", "FuelCellExhaustAfterCatalytycBurner", "VarName67"];
opts.VariableTypes = ["double", "double", "double", "string", "double", "double", "double", "double", "double", "string", "double", "double", "string", "double", "string", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName4", "VarName10", "VarName13", "VarName15", "VarName18", "VarName27", "VarName36", "VarName37", "VarName38", "VarName39", "VarName47", "VarName56", "VarName65"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName4", "VarName10", "VarName13", "VarName15", "VarName18", "VarName27", "VarName36", "VarName37", "VarName38", "VarName39", "VarName47", "VarName56", "VarName65"], "EmptyFieldRule", "auto");

% Import the data
ReformerPlusStackDatasmall = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/backend/TimeSeries/AGRO_SOFC/SOFC-REFORMER/2021-03-04-SOFC-REFORMER-Martin/A000_RelatedFiles/ReformerPlusStackData_small.csv", opts);


%% Clear temporary variables
clear opts