clear 

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/backend/TimeSeries/Horti_MED/SPAIN/CLIMA/2020_01_13_sysclima/A001_UniformFormat/Producción_Menaka.xlsx
%    Worksheet: Datos brutos
%
% Auto-generated by MATLAB on 14-Jan-2021 08:28:50

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "Datos brutos";
opts.DataRange = "A4:H329";

% Specify column names and types
opts.VariableNames = ["FechaDeEntrega", "CdProducto", "DescripcinProducto", "Envase", "CantidadEnvases", "Bruto", "TaraEnvases", "Netokg"];
opts.VariableTypes = ["datetime", "categorical", "categorical", "categorical", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["CdProducto", "DescripcinProducto", "Envase"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "FechaDeEntrega", "InputFormat", "");

% Import the data
ProduccinMenaka = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/backend/TimeSeries/Horti_MED/SPAIN/CLIMA/2020_01_13_sysclima/A000_RelatedFiles/Producción_Menaka.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
dataset01 = ProduccinMenaka;
save("" + MainPath + 'TimeSeries/Horti_MED/PROD/2020_01_13_PROD/A001_UniformFormat/output/dataset01.mat','dataset01')