clear 
load(MainPath+"/TimeSeries/Horti_MED/SPAIN/CLIMA/2020-04-26-SYSCLIMA/A001_UniformFormat/output/Ts_sysclima_01.mat")
%%
% iTs = RemoveVars(iTs,'verbose',1,'rmvars',{'EstadoLateralE','Sonda1','Sonda2', ...
%                                            'Sonda3','Sonda5','Sonda6', ...
%                                            'Aerotermo1Activo','DeltaT','DeltaX', ...
%                                            'MaxHR','Troco','RadAcumExt', ...
%                                            'TVentilacin','DPV',});

%
iTs = RemoveVars(iTs,'verbose',1,'rmvars',{'EstadoLateralE','Sonda1','Sonda2', ...
                                           'Sonda3','Sonda5','Sonda6', ...
                                           'Aerotermo1Activo','DeltaT','DeltaX', ...
                                           'Troco','RadAcumExt', ...
                                           'DPV',});
%%
xlims = [datetime('2018-02-20') datetime('2018-02-25')];
ShowData(iTs,'xlim',[])
%%
pathfile = fullfile(MainPath,'TimeSeries','Horti_MED','SPAIN','CLIMA', ...
                    '2020-04-26-SYSCLIMA','A001_UniformFormat', ...
                    'output','Ts_sysclima_02.mat');

save(pathfile,'iTs')