%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/izaro/año2019completo.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 02-Jun-2021 16:14:39

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "A1:E52560";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5"];
opts.VariableTypes = ["double", "string", "double", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "VarName4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "VarName4"], "EmptyFieldRule", "auto");

% Import the data
ano2019completo = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/ModellingAndControl/izaro/año2019completo.xlsx", opts, "UseExcel", false);

ano2019completo = ano2019completo(:,[1 3 5]);
ano2019completo.Properties.VariableNames = {'T','R','V'};
%% Clear temporary variables
clear opts
%%
time = 600*(0:4463)';
time = 600*(0:length(ano2019completo.T)-1)';
t = ano2019completo.T;
tt = timetable(seconds(time),t);
%
si = ano2019completo.R;
Si = timetable(seconds(time),si);
%
v = ano2019completo.V;
vv = timetable(seconds(time),v);

Tref = 16.5;
%%
